labs/rails/coffeeshop_app/config/routes.rb
Rails.application.routes.draw do

root 'beans#index'

get '/beans'=> 'beans#index'

post '/beans'=> 'beans#create'

get '/beans/new/' => 'beans#new', as: :new_bean

get '/beans/:id' => 'beans#show', as: :bean

get 'beans/:id/edit'=> 'beans#edit', as: :edit_bean

patch '/beans/:id'=> 'beans#update'
delete '/beans/:id' => 'beans#destroy'

get '/beans/:id/edit' => 'beans#edit', ad: :edit_bean

end

labs/rails/coffeeshop_app/app/models/bean.rb
class Bean < ActiveRecord::Base
end

labs/rails/coffeeshop_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

labs/rails/coffeeshop_app/app/controllers/beans_controller.rb
class BeansController < ApplicationController

before_action :set_bean, only: [:show,:edit,:update, :destroy]
# says before you exicute actions, run the private method, only for the [items]
  def index
    @beans = Bean.all
  end



  def show
    # @bean = Bean.find(params[:id    #taken out due to private method and before action intialization])
    # find the postgress created id through the database and put it in the @bean variable
    # params look in the uri, look in that spot and take that value and put it into thes search
  end


  def new
    @bean = Bean.new
  end



  def create
    @bean = Bean.new(bean_params)
# @instance variable
# bean.new active record
# params giving the database a beans hash
# .permit goes into the hash, "whitelisting" or accepting the vales
 #creating new bean, requiring the bean key in the new hash,
    if @bean.save
    #if it saves to database, shows the index


    # redirect_to beans_path  #goes to index
     redirect_to bean_path(@bean) #goes to show page

  else #if it does not save, render the form again so you can try again
    render :new
  end
end



def edit
  # @bean = Bean.find(params[:id])    #taken out due to private method and before action intialization
end



def update
  # @bean = Bean.find(params[:id])    #taken out due to private method and before action intialization

  if @bean.update_attributes(bean_params)
  redirect_to bean_path
else
  render :edit
end
end


def destroy
  # @bean = Bean.find(params[:id])    #taken out due to private method and before action intialization
  @bean.destroy
  redirect_to beans_path
end

  private

    def set_bean
      @bean = Bean.find(params[:id])
    end



    def bean_params
      params.require(:bean).permit(:name, :roast,:origin,:quantity)
    end






end

labs/rails/coffeeshop_app/app/helpers/application_helper.rb
module ApplicationHelper
end

labs/rails/coffeeshop_app/app/helpers/beans_helper.rb
module BeansHelper
end

labs/rails/coffeeshop_app/app/views/beans/_form.html.erb
<%= form_for @bean do |f| %>


<div>
  <%=f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :roast %>
  <%= f.text_field :roast %>
</div>

<div>
  <%= f.label :origin %>
  <%= f.text_field :origin %>
</div>

<div>
  <%= f.label :quantity %>
  <%= f.text_field :quantity, :step => 'any' %>
</div>

  <%= f.submit %>
  <% end %>


<%= link_to "Back to the list!", beans_path %>

labs/rails/coffeeshop_app/app/views/beans/edit.html.erb
<h1> Edit yo bean!</h1>

<%= render 'form' %>

labs/rails/coffeeshop_app/app/views/beans/index.html.erb
<h1> Today's Beans</h1>
<ul>
  <% @beans.each do |bean| %>
    <li>
      <strong> <%= link_to bean.name, bean_path(bean)%> </strong> - <%= bean.roast %>
    </li>
  <%end %>
</ul>

<%= link_to 'Add a bean!', new_bean_path %>

labs/rails/coffeeshop_app/app/views/beans/new.html.erb
_<h1> Add a new bean!</h1>

<%= render 'form' %>

labs/rails/coffeeshop_app/app/views/beans/show.html.erb
<h1> <%= @bean.name %></h1>

<p>
This is a <%= @bean.roast %> roast from <%= @bean.origin %>, and we have <%= @bean.quantity %>
pounds availaaalalallabe.

</p>


<%= link_to 'Edit this bean!', edit_bean_path %>
<%= link_to "Delete this bean!", bean_path, method: :delete, data:{confirm:'Are you sure?'} %>
<br>
<%= link_to "Back to the list!", beans_path %>


<!-- this is a view created to populate the views on different routes and gets populated with various bean paramaters -->

labs/rails/coffeeshop_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffeeshopApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>